[package]
name = "Insurance-Claims-Processing"
version = "1.0.0"
authors = []

[addresses]
MyModule="0x8bc2a519b4e01ba0de2353ee5192ff0f0769f7862e8257d6a11fa870c83d1615"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
